# ZMK GitHub Actions build matrix for Corne (Nice!Nano v2 + nice!view)
include:
  # Central half — WPM + USB controller lives here
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: corne_left_central

  # Peripheral half — runs the Bongo Cat animation
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view nice-view-mod
    snippet: studio-rpc-usb-uart
    artifact-name: corne_right_peripheral
